### ISSUE TITLE
what is the usage of Procfile ?

### ISSUE THREAD

**Issue by massooti** [HackSoftware/Django-Styleguide-Example#382]
Hi guys, 

simple question, or maybe silly question but

what is the usage of **Procfile**, which is in the root of project

how can i use it? 

thank you in advanced

**Comment by Ivaylo-Bachvarov** [comment]
Key @massooti 

The Procfile is what Heroku uses in order to start the application.

If you are using Heroku to host your project you need a Procfile. If you are using something else the example Procfile gives a good understanding on how to start all needed processes.

Reference: https://devcenter.heroku.com/articles/procfile
